name: mdde
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - jupyterlab=3
    - pyyaml
    # linters and more
    - pylint
    - pycodestyle
    - pydocstyle
    - black
    # Parquet tools
    - parquet-tools
    - pip:
        - watermark
        - -r ../requirements.txt
